name: Run AdonisJS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to Backend
        working-directory: ./backend
        run: echo "Changed to /backend directory"

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Copy .env.example
        working-directory: ./backend
        run: cp .env.example .env

      - name: Wait for Redis
        run: |
          until redis-cli ping; do
            echo "Waiting for Redis..."
            sleep 1
          done

      - name: Generate APP_KEY
        working-directory: ./backend
        run: node ace generate:key

      - name: Run Tests
        working-directory: ./backend
        run: npm test